### ISSUE TITLE
Adapt dataservices-api to functions that return tables

### ISSUE THREAD

**Issue by iriberri** [CartoDB/dataservices-api#175]
cc @rafatower @javisantana 

Affected functions:

````
- name: obs_getboundariesbygeometry
  return_type: TABLE(the_geom geometry, geom_refs text)
  params:
    - { name: geom,  type: "geometry(Geometry, 4326)" }
    - { name: boundary_id, type: text }
    - { name: time_span, type: text, default: 'NULL'}
    - { name: overlap_type, type: text, default: "'intersects'"}

- name: obs_getboundariesbypointandradius
  return_type: TABLE(the_geom geometry, geom_refs text)
  params:
    - { name: geom,  type: "geometry(Geometry, 4326)" }
    - { name: radius, type: numeric }
    - { name: boundary_id, type: text }
    - { name: time_span, type: text, default: 'NULL'}
    - { name: overlap_type, type: text, default: "'intersects'"}

- name: obs_getpointsbygeometry
  return_type: TABLE(the_geom geometry, geom_refs text)
  params:
    - { name: geom,  type: "geometry(Geometry, 4326)" }
    - { name: boundary_id, type: text }
    - { name: time_span, type: text, default: 'NULL'}
    - { name: overlap_type, type: text, default: "'intersects'"}

- name: obs_getpointsbypointandradius
  return_type: TABLE(the_geom geometry, geom_refs text)
  params:
    - { name: geom,  type: "geometry(Geometry, 4326)" }
    - { name: radius, type: numeric }
    - { name: boundary_id, type: text }
    - { name: time_span, type: text, default: 'NULL'}
    - { name: overlap_type, type: text, default: "'intersects'"}

- name: obs_search
  return_type: TABLE(id text, description text, name text, aggregate text, source text)
  params:
    - { name: search_term, type: text }
    - { name: relevant_boundary, type: text, default: 'NULL' }

- name: obs_getavailableboundaries
  return_type: TABLE(boundary_id text, description text, time_span text, tablename text)
  params:
    - { name: geom,  type: Geometry }
    - { name: time_span, type: text, default: 'NULL'}
````
