### ISSUE TITLE
Make 3rd party services URL's configurable

### ISSUE THREAD

**Issue by rporres** [CartoDB/dataservices-api#343]
HERE has an offering of offline maps, so we need to be able to configure URL through `CDB_CONF`. It is currently hardcoded in https://github.com/CartoDB/dataservices-api/blob/development/server/lib/python/cartodb_services/cartodb_services/here/geocoder.py#L15 but prepared more or less to pass it as a parameter in https://github.com/CartoDB/dataservices-api/blob/development/server/lib/python/cartodb_services/cartodb_services/here/geocoder.py#L56

cc @javisantana 

**Update:** there are other services with hardcoded URL's.E.g: [mapzen isochrones]( https://github.com/CartoDB/dataservices-api/blob/7c816be5e5f99cd26d510774e1e23d1c4f282dfa/server/lib/python/cartodb_services/test/test_mapzenisochrones.py#L13). They should be configurable just like other settings (see the [configuration for different services](https://github.com/CartoDB/dataservices-api#local-install-instructions) ) and pick the hardcoded value as default only when absent.

**Comment by javisantana** [comment]
good catch @rporres

**Comment by javisantana** [comment]
hey, i'd like to see the approach here before moving on

**Comment by rafatower** [comment]
We'll discuss general reqs for config stuff here in this ticket

**Comment by jgoizueta** [comment]
# Background/Reference Information

We have three sources of dataservices configuration

* The Server (stored in DS server database in `cdb_conf` table)
* The User (stored in redis under `rails:users:{USER}` keys)
* The Organization (stored in redis under `rails:orgs:{ORG}` keys)

The DS server configuration is provisioned by chef, from node attributes assigned per environment:

* [production](https://github.com/CartoDB/cartodb-platform/blob/3af43aabfbeb280a39bdfd42c36fb6d5811cf773/environments/production.json#L195)
* [onpremises](https://github.com/CartoDB/cartodb-platform/blob/3af43aabfbeb280a39bdfd42c36fb6d5811cf773/environments/onpremises.json) (no ds config)
* [staging](https://github.com/CartoDB/cartodb-platform/blob/3af43aabfbeb280a39bdfd42c36fb6d5811cf773/environments/staging.json#L409)

The User and Organization configuration is managed by central, stored in its database and propagated through the boxes to redis metadata.

## Unfinished refactor

This refactor is in use for the Mapzen geocoding configuration.

It makes the configuration level (server, user, organization) and its storage independent (so configuration could be moved from db/redis etc.).
This is done by having separate classes for each different aspect/concern: storage (in memory, redis, database), used by the different backends (server, organization, user), an these in turned used by services.

## Configuration contents:

### cdb_conf (server database)

```
geocoder_server_config: connection_str
user_config: is_organization, entity_name
redis_metadata_config: redis_host, redis_port,  sentinel_master_id, timeout, redis_db
redis_metrics_config:  redis_host, redis_port,  sentinel_master_id, timeout, redis_db
heremaps_conf:
    geocoder: app_id, app_code, geocoder_cost_per_hit
    isolines: app_id, app_code
mapzen_conf:
    routing: api_key, monthly_quota
    geocoder: api_key, monthly_quota,
    matrix: api_key, monthly_quota
logger_conf: geocoder_log_path, routing_log_path, isolines_log_path, do_log_path, min_log_level, rollbar_api_key, log_file_path
data_observatory_conf:
    connection: whitelist, production, staging
    monthly_quota
server_conf: environment
fdws:
    aggregation:
        server: extensions, dbname, host, port
    users:
        public: user, password
````

### user/org (redis)

```
geocoder_provider
isolines_provider
routing_provider
geocoding_quota
here_isolines_quota
obs_snapshot_quota
obs_general_quota
mapzen_routing_quota
soft_here_isolines_limit
soft_obs_general_limit
soft_obs_snapshot_limit
soft_mapzen_routing_limit
google_maps_client_id
google_maps_api_key
map_key
```

# Currently non-configurable Parameters, per service

### Here Geocoder

```ruby
PRODUCTION_GEOCODE_JSON_URL = 'https://geocoder.api.here.com/6.2/geocode.json'
STAGING_GEOCODE_JSON_URL = 'https://geocoder.cit.api.here.com/6.2/geocode.json' # not used
DEFAULT_MAXRESULTS = 1
DEFAULT_GEN = 9
READ_TIMEOUT = 60
CONNECT_TIMEOUT = 10
MAX_RETRIES=1
```

Defined in `HereMapsGeocoder` (server/lib/python/cartodb_services/here/geocoder.py),
instantiated from `cdb_dataservices_server._cdb_here_geocode_street_point` (server/extension/sql/20_geocode_street.sql)

### Here Isolines

```ruby
PRODUCTION_ROUTING_BASE_URL = 'https://isoline.route.api.here.com'
STAGING_ROUTING_BASE_URL = 'https://isoline.route.cit.api.here.com'
ISOLINE_PATH = '/routing/7.2/calculateisoline.json'
READ_TIMEOUT = 60
CONNECT_TIMEOUT = 10
MAX_RETRIES = 1
```

Defined in `HereMapsRoutingIsoline` (server/lib/python/cartodb_services/here/routing.py),
instantiated from `cdb_dataservices_server._cdb_here_routing_isolines` (server/extension/sql/80_isolines_helper.sql).

### Google Geocoder

Implemented in `GoogleMapsGeocoder` (server/lib/python/cartodb_services/google/geocoder.py),
this is a very different case: the `googlemaps` module hides connections details and
the credentials are individual for each user (`google_maps_client_id` and `google_maps_client_id` in redis)

Instantiated from `cdb_dataservices_server._cdb_google_geocode_street_point` (server/extension/sql/20_geocode_street.sql).

### Mapzen Geocoder

```ruby
BASE_URL = 'https://search.mapzen.com/v1/search'
READ_TIMEOUT = 60
CONNECT_TIMEOUT = 10
MAX_RETRIES = 1
```

Defined in `MapzenGeocoder` ( server/lib/python/cartodb_services/mapzen/geocoder.py),
instantiated from `cdb_dataservices_server._cdb_mapzen_geocode_street_point` (server/extension/sql/20_geocode_street.sql).

This is the one service that is currently using the new refactored configuration system, which involves
instantiating `ServerConfigBackendFactory`, `ServerEnvironmentBuilder`, `UserConfigBackendFactory`, `OrgConfigBackendFactory`
and finally `MapzenGeocoderConfigBuilder` which is the one that provides the parameters passed to `MapzenGeocoder`.

### Mapzen Isolines

For isochrones:

```ruby
BASE_URL = 'https://matrix.mapzen.com/isochrone'
READ_TIMEOUT = 60
CONNECT_TIMEOUT = 10
MAX_RETRIES = 1
```

Defined in `MapzenIsochrones` (server/lib/python/cartodb_services/mapzen/isochrones.py), and
instantiated from `cdb_dataservices_server._cdb_mapzen_isochrones` (server/extension/sql/80_isolines_helper.sql).

For isolines:

```
NUMBER_OF_ANGLES = 24
MAX_ITERS = 5
TOLERANCE = 0.1
```

Defined in `MapzenIsolines` (server/lib/python/cartodb_services/mapzen/isolines.py) and using the matrix service:

```ruby
ONE_TO_MANY_URL = 'https://matrix.mapzen.com/one_to_many'
READ_TIMEOUT = 60
CONNECT_TIMEOUT = 10
```

Defined in `MatrixClient` (server/lib/python/cartodb_services/mapzen/matrix_client.py),
and instantiated from `db_dataservices_server._cdb_mapzen_isodistance` ( server/extension/sql/80_isolines_helper.sql)

### Mapzen Routing

```
PRODUCTION_ROUTING_BASE_URL = 'https://valhalla.mapzen.com/route'
READ_TIMEOUT = 60
CONNECT_TIMEOUT = 10
MAX_RETRIES=1
```

Defined in `MapzenRouting` (server/lib/python/cartodb_services/mapzen/routing.py),
instantiated from `cdb_dataservices_server._cdb_mapzen_route_with_waypoints` (server/extension/sql/100_routing_helper.sql)
